### ISSUE TITLE
Rubygems is unreachable

### ISSUE THREAD

**Issue by professor** [pivotal/projectmonitor#101]
I'd like to suggest that we remove the banner warnings. They seem to occur frequently. It's more noise than signal. Maybe the url changed? If rubygems is down, I'll probably discover it pretty quickly.

Ditto for heroku, github, and the other warning messages.

**Comment by andistuder** [comment]
Instead of removing, maybe allow disabling via environment variable? 
Further, as discussed in #97 and #98, it would be better to query the Rubygems status page instead of parsing the webpage.

**Comment by professor** [comment]
If someone is relying on this behavior, maybe have it be configurable per project monitor. I believe most of us in Palo Alto just ignore it. It is a little embarrassing to have it show up during tours. I had assumed (maybe incorrectly) that it is vestigial code.

**Comment by schubert** [comment]
Does https://github.com/pivotal/projectmonitor/pull/98 fix this?

**Comment by andistuder** [comment]
As mentioned on #98 (and #97 which is fix for same issue), it would be better to get the status via JSON API request, instead of parsing the html. 

I wrote a fix [here](https://github.com/andistuder/projectmonitor/commit/edf391627a30aeb6d4317070fc8810d8d9bae254) building on @Khoulaiz's #97, but waiting to get it adopted.

**Comment by tjgrathwell** [comment]
I merged in @andistuder's branch, things should be okay now.

I don't deny that the warnings have done more harm than good in the recent past, but hopefully if we can keep on top of these status changes (better than this many-month turnaround 😿 ) it won't be so bad going forward. I think a pull request that does the disable-by-env-variable thing would be cool too.
