### ISSUE TITLE
Editing existing job with multiple tags clobbers commas

### ISSUE THREAD

**Issue by lennyk** [pivotal/projectmonitor#104]
When we edit a job that has multiple tags, the tags in the text field are missing commas. They then get combined into one tag.

Should be:
<img width="601" alt="screen shot 2016-04-21 at 12 25 10 pm" src="https://cloud.githubusercontent.com/assets/4040241/14718414/29108162-07bc-11e6-95d0-cb4594d835e4.png">

Currently is:
<img width="600" alt="screen shot 2016-04-21 at 12 25 00 pm" src="https://cloud.githubusercontent.com/assets/4040241/14718429/3dd5d142-07bc-11e6-86e5-d579eba410cd.png">

**Comment by tjgrathwell** [comment]
It's a regression from upgrading to Rails 4.2, more detail at https://github.com/mbleigh/acts-as-taggable-on/wiki/Add-a-tag-field-to-forms-in-Rails--4.2-and-above

Fix incoming, thanks for reporting!
