### ISSUE TITLE
Unable to install projectmonitor on Ubuntu

### ISSUE THREAD

**Issue by juliusblank** [pivotal/projectmonitor#109]
After several unsuccessful attempts to get projectmonitor running under Ubuntu 16.04, I need assistance.
I followed the installation instructions and when it comes to `bundle install`, the setup always exits when it tries to install `capybara-webkit-1.11.1`, stating that no installation of QtWebkit can be found:

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1
    /home/railer/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20170113-13645-1oy1llf.rb extconf.rb
    cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake/tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1/src/webkit_server.pro -o Makefile.webkit_server) && make -f Makefile.webkit_server
    Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
    Makefile:42: recipe for target 'sub-src-webkit_server-pro-make_first-ordered' failed make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3 Command 'make' failed

    current directory: /tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1
    make "DESTDIR=" clean cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake/tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1/src/webkit_server.pro -o Makefile.webkit_server) && make -f Makefile.webkit_server clean
    Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
    Makefile:54: recipe for target 'sub-src-webkit_server-pro-clean-ordered' failed make: *** [sub-src-webkit_server-pro-clean-ordered] Error 3

     current directory: /tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1
    make "DESTDIR=" cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake/tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1/src/webkit_server.pro -o Makefile.webkit_server) && make -f Makefile.webkit_server
    Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
    Makefile:42: recipe for target 'sub-src-webkit_server-pro-make_first-ordered' failed
    make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3

    make failed, exit code 2

    Gem files will remain installed in /tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/gems/capybara-webkit-1.11.1 for inspection.
    Results logged to /tmp/bundler20170113-13645-1c9k4blcapybara-webkit-1.11.1/extensions/x86_64-linux/2.3.0-static/capybara-webkit-1.11.1/gem_make.out

    An error occurred while installing capybara-webkit (1.11.1), and Bundler cannot continue.
    Make sure that `gem install capybara-webkit -v '1.11.1'` succeeds before bundling.

My system info:

    ruby -v
    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

    rails -v
    Rails 5.0.1

    qmake -v
    QMake version 3.0
    Using Qt version 5.5.1 in /home/myuser/.linuxbrew/Cellar/qt@5.5/5.5.1/lib

I treid the same with Qt 5.7.1 (installed via (linux) `brew install qt`), with the same error.

Could you please help me out as to where I can look for a solution?

Thanks a lot in advance!

**Comment by carpeliam** [comment]
I'm seeing in your error message:
```
Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
```

Have you tried installing QtWebKit separately?

**Comment by juliusblank** [comment]
Hi carpeliam,

yes, I have. 
Both via `apt-get install libqt5webkit5` (for use with qt 5.7.1) or via manually installing `brew install qt@5.5` (which should tisll contain QtWebKit) I keep getting the error.

**Comment by juliusblank** [comment]
Could you please give me some more details about the system you use for building projectmonitor?

**Comment by schjan** [comment]
Try install `libqt5webkit5-dev` instead.

**Comment by arcioneo** [comment]
I am having the same issue, the details about my system are:

```
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

Homebrew 1.2.1
Homebrew/homebrew-core (git revision 1bc2; last commit 2017-06-25)

$: qtchooser -l
4
5
default
qt4-x86_64-linux-gnu
qt4
qt5-x86_64-linux-gnu
qt5

```

The error I get when running `bundle install` 


```
/usr/bin/ruby2.3 -r ./siteconf20170627-16100-1522afr.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-gl-dir
        --without-gl-dir
        --with-gl-include
        --without-gl-include=${gl-dir}/include
        --with-gl-lib
        --without-gl-lib=${gl-dir}/lib
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
Command 'qmake ' not available

extconf failed, exit code 1

```

```
An error occurred while installing capybara-webkit (1.11.1), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.11.1'` succeeds before bundling.
```

**Comment by arcioneo** [comment]
After restarting and installing all the needed libraries I'm getting this:

```
eduardo@linux-01:~/git/projectmonitor$ bundle install
Killed
eduardo@linux-01:~/git/projectmonitor$ 
```

**Comment by arcioneo** [comment]
@juliusblank I had the same issue, try:
```
apt-get install --reinstall qtchooser
```

that fixed my problem

**Comment by stephencoe** [comment]
A full list of dependencies for capybara can be found in the [capybara wiki](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#debian--ubuntu)

**Comment by pivotal-kahin-ng** [comment]
We now ship the [Dockerfile](https://github.com/pivotal/projectmonitor/blob/master/Dockerfile) running ubuntu. Updated README also includes usage instructions. Cheers!
