### ISSUE TITLE
Unable to view status of TeamCity build and build history

### ISSUE THREAD

**Issue by bensullivan** [pivotal/projectmonitor#83]
Hi

Apologies if this isn't the right place to ask this - the Google group looks pretty quiet so I wasn't sure if it was still being used.  I fired up ProjectMonitor yesterday at a local TC 9.1 instance.  I can login and create projects and my CI Status in the polled build setup is OK.  However, when I view the dashboard the tile colour reflects a status that looks neither passed nor failed and there is no history either.  The Last Polling Status of the project on the Configuration page remains at None.

I have set the fetch status for every minute but nothing appears to change and there does not appear to be any fetch_statuses.log file in the log directory.

I will continue debugging but I was wondering if this might be an issue with TC 9.1 perhaps?

Any assistant for troubleshooting would be greatly appreciated.

Many thanks

Ben Sullivan

**Comment by bensullivan** [comment]
Apologies - hadn't switched whenever to development environment.

**Comment by SQUIDwarrior** [comment]
I have this same problem, but I can't seem to get past it. Could you tell me how you configured ProjectMonitor?

**Comment by bensullivan** [comment]
Hi

Yeah first of all I had to switch my environment to development for the whenever gem as we havn't gone to production yet and it appears as though the default is production.

Then I had to try a few different things to get whenever to actually update my crontab - I think I went with `whenever -w` in the end.  Just make sure you can see the cron entries.

I was running on Linux so I also had to install the qt dependency without brew.

Cheers

Ben

**Comment by SQUIDwarrior** [comment]
Thanks for the reply! My crontab is set up to run the tasks, but they don't seem to do anything. I see them running, but nothing is going into the fetch_statuses.log. Running the rake fetch task manually doesn't produce any output. 

I've tried using both production and development environments, and neither seem to work.

**Comment by bensullivan** [comment]
Can you see anything in the relevant project monitor tables to suggest projectmonitor is talking to your CI server when fetch statuses runs?  What CI server are you using?  We're running TeamCity 9...

**Comment by SQUIDwarrior** [comment]
I am using TeamCtiy 9.0.2. In the ProjectMonitor config screen, i get a green "OK" when I click the "refresh" button. 

And you are right, the project_statuses table is empty. I did notice that the "rake dependency:fetch_statuses" task in the crontab is throwing an error and failing. I opened up a new issue for that one.

When I run "rake projectmonitor:fetch_statuses" manually I get no output.
