### ISSUE TITLE
Regarding project monitor

### ISSUE THREAD

**Issue by AjayKV123** [pivotal/projectmonitor#90]
Hi Team,
Can you kindly provide me list of software's to download to host projectmonitor.

And also, it will be helpful if you send step wise installation guide .
Since i am a beginner, step wise installation will do great help for me.

Thanks,
Ajay

**Comment by dideler** [comment]
Installation steps and a place to host the app (e.g. Heroku) are already covered in the [README](https://github.com/pivotal/projectmonitor#readme). Do you have any specific suggestions for what could be improved?
