### ISSUE TITLE
Photo of Project Monitor in use

### ISSUE THREAD

**Issue by jonathanpberger** [pivotal/projectmonitor#94]
I'm trying to explain what it looks like to have public CI in an office. It'd be very helpful to see a photo of Project Monitor in the wild as an example for folks who don't have TVs w/ CI mounted on the wall. Could someone post a pic of a TV with some public-viewable (open source?) builds to the README? cc @infews (Hi Davis! :-)

**Comment by dideler** [comment]
There's some photos at https://blog.pivotal.io/labs/labs/lessons-from-the-beach and http://www.geodessica.com/CI-Monitor, but you'll need to ask those authors for permission. Or we could link to those blog posts as examples instead of using the images in the README.

**Comment by jonathanpberger** [comment]
Thanks for finding those photos! Unfortunately I don't think they do the trick.

The problem I'm trying to solve is "how do I *show* (not tell) the benefits of CI and real-world daily use patterns to folk who're unfamiliar with it?" In order to do that, screenshots (and even the monitor on the concrete column in Jessica's pic) aren't sufficient. I want a shot of an office with multiple CI monitors on the wall to demonstrate how pervasive and transparent good CI is, and what it looks like in the context of a working office. (E.g., a photo that does for CI what [this image](http://jonathanpberger.github.io/presentation_pair_design-asbury-agile/images/office-pairing.gif) does for pairing.)

**Comment by jonathanpberger** [comment]
PR #96 created to fix this. https://github.com/pivotal/projectmonitor/pull/96

**Comment by odlp** [comment]
Closing this issue since the PR was merged :+1:
