### ISSUE TITLE
Semaphore Polling doesn't function

### ISSUE THREAD

**Issue by mkanthan** [pivotal/projectmonitor#99]
When adding a polling project for Semaphore, a check for branch name from the response returns false since the key doesn't exist where it's referenced in semaphore_payload.rb:

```
def specified_branch?(content)
  branch == content['branch_name']
end
```

The problem here is that key `branch_name` doesn't appear in the content object which is a nested build inside the response.  It appears in the top-level response object now (maybe it worked at the time it was written) and so it breaks polling on Semaphore projects.  I'll see if I can take a stab at fixing this and submitting a PR.

**Comment by tjgrathwell** [comment]
Should be fixed now, sorry for the wait.
